export const STORAGE_TEST_ENV = {
  OBJECT_STORAGE_DRIVER: 'memory',
  OBJECT_STORAGE_FORCE_PATH_STYLE: 'false',
  EXERCISE_MEDIA_UPLOAD_TTL_SECONDS: '600',
  EXERCISE_MEDIA_READ_TTL_SECONDS: '120',
  EXERCISE_VIDEO_MAX_BYTES: '262144000',
  EXERCISE_IMAGE_MAX_BYTES: '10485760',
  PROGRESS_PHOTO_MAX_BYTES: '10485760',
};
