import { createLiveCopy, registerEnglishNamespace } from '@/i18n/live-copy';
import { useLiveCopy } from '@/i18n/use-live-copy';

export const trainingAssistantCopySource = {
  name: 'Training Assistant',
  launcherLabel: 'Open Training Assistant',
  closeLabel: 'Close Training Assistant',
  description: 'Ask how the platform works. Answers are generated by AI and may contain mistakes.',
  greeting:
    'Hi! 👋 I’m Training Assistant. I can help you understand your training, nutrition, progress, and how the platform works. How can I help?',
  quickPromptsLabel: 'Suggested questions',
  quickPrompts: {
    howItWorks: 'How does it work?',
    training: 'Training',
    nutrition: 'Nutrition',
    progress: 'Progress',
    help: 'I need help',
  },
  public: {
    description:
      'Ask what the platform does. Don’t share personal or health details here. Answers are generated by AI and may contain mistakes.',
    greeting:
      'Hi! 👋 I’m Training Assistant. I can explain what Training is, how it works, and how to get started. What would you like to know?',
    quickPrompts: {
      howItWorks: 'How does it work?',
      start: 'How do I get started?',
      plans: 'Plans',
      training: 'Training',
      nutrition: 'Nutrition',
      progress: 'Progress',
    },
  },
  composer: {
    label: 'Message for Training Assistant',
    placeholder: 'Type your message...',
    send: 'Send message',
    hint: 'Enter to send, Shift + Enter for a new line',
    remaining: '{{count}} characters left',
  },
  you: 'You',
  typing: 'Training Assistant is typing…',
  status: {
    CONNECTING: 'Connecting…',
    CONNECTED: 'Online',
    RECONNECTING: 'Reconnecting…',
    DISCONNECTED: 'Offline',
    ERROR: 'Unavailable',
  },
  banner: {
    reconnecting: 'Connection lost. Trying to reconnect...',
    disconnected: 'You are offline from the assistant.',
    error: 'The assistant is unavailable right now.',
    sessionExpired: 'Your session ended. Sign in again to keep chatting.',
    tooManyConnections: 'The assistant is open in too many tabs. Close one and try again.',
    reconnect: 'Reconnect',
  },
  errors: {
    AI_UNAVAILABLE: 'I can’t generate a reply right now. Please try again in a few moments.',
    QUOTA_EXHAUSTED:
      'The public assistant reached its message limit for today. If you have an account, sign in to keep chatting.',
    RATE_LIMITED: 'You’re sending messages too quickly. Wait a moment and try again.',
    BUSY: 'Wait for the current reply to finish.',
    MESSAGE_TOO_LONG: 'That message is too long.',
    INVALID_MESSAGE: 'That message could not be sent.',
    CONNECTION_LOST: 'The connection was lost before the reply arrived.',
    TIMEOUT: 'The reply took too long.',
    GENERIC: 'The message could not be sent.',
  },
  retry: 'Retry',
} as const;

registerEnglishNamespace('trainingAssistant', trainingAssistantCopySource);
export const trainingAssistantCopy =
  createLiveCopy<typeof trainingAssistantCopySource>('trainingAssistant');

export function useTrainingAssistantCopy() {
  return useLiveCopy<typeof trainingAssistantCopySource>('trainingAssistant');
}
