export const EXERCISE_NAME_MIN_LENGTH = 2;
export const EXERCISE_NAME_MAX_LENGTH = 150;
export const EXERCISE_DESCRIPTION_MAX_LENGTH = 2_000;
export const EXERCISE_INSTRUCTIONS_MAX_LENGTH = 5_000;
export const EXERCISE_SEARCH_MAX_LENGTH = 100;
export const EXERCISE_LIST_DEFAULT_PAGE = 1;
export const EXERCISE_LIST_DEFAULT_LIMIT = 20;
export const EXERCISE_LIST_MAX_LIMIT = 100;
