export const TRAINER_PHONE_MAX_LENGTH = 32;
export const TRAINER_TITLE_MAX_LENGTH = 120;
export const TRAINER_BIO_MAX_LENGTH = 2_000;
export const TRAINER_SEARCH_MAX_LENGTH = 100;
export const TRAINER_LIST_DEFAULT_PAGE = 1;
export const TRAINER_LIST_DEFAULT_LIMIT = 20;
export const TRAINER_LIST_MAX_LIMIT = 100;
