import { createLiveCopy, registerEnglishNamespace } from '@/i18n/live-copy';
import { useLiveCopy } from '@/i18n/use-live-copy';

export const clientNutritionCopySource = {
  title: 'Nutrition',
  description: 'Your current assigned plan. These are prescribed targets, not food you have eaten.',
  loadingLabel: 'Loading nutrition plan',
  emptyTitle: 'No nutrition plan is assigned yet.',
  emptyBody: 'Your coach will assign a plan. Meals and daily targets will appear here.',
  prescribedHint: 'This is a prescribed plan, not a log of what you ate.',
  plan: {
    eyebrow: 'Current plan',
    statusActive: 'Active',
    statusArchived: 'Archived',
    statusDraft: 'Draft',
    from: 'From',
    until: 'Until',
  },
  targets: {
    title: 'Daily targets',
    description: 'Prescribed amounts for this plan. Not calories remaining or consumed.',
    calories: 'Calories',
    protein: 'Protein',
    carbs: 'Carbs',
    fat: 'Fat',
    none: 'No daily targets are set on this plan.',
    macroChart: 'Share of prescribed protein, carbohydrate, and fat targets',
    plannedProgress: 'Planned meal calories versus the prescribed daily target',
    plannedOfTarget: '{{planned}} planned of {{target}} prescribed',
  },
  totals: {
    title: 'Plan information',
    dailyTarget: 'Daily target',
    mealTotal: 'Planned meal total',
    difference: 'Difference',
    differenceHint:
      'Planned meal total minus the daily target. This is not remaining calories or intake.',
    meals: 'Meals',
    meal: 'Meal',
    comparison: 'Planned nutrients vs daily targets',
    planned: 'Planned',
    target: 'Target',
    noTarget: 'No target set',
    savedHint: 'Values from the saved meal plan. Differences are planned amounts minus targets.',
  },
  meals: {
    title: 'Day plan',
    description: 'Assigned meals, grouped from breakfast through dinner.',
    glance: 'Meal summary',
    empty: 'No meals are listed on this plan yet.',
    noFoods: 'No foods listed.',
    notes: 'Notes',
    calories: 'Calories',
    protein: 'Protein',
    carbs: 'Carbs',
    fat: 'Fat',
    fiber: 'Fiber',
  },
  foods: {
    quantity: 'Amount',
  },
  mealType: {
    BREAKFAST: 'Breakfast',
    LUNCH: 'Lunch',
    DINNER: 'Dinner',
    SNACK: 'Snack',
    OTHER: 'Other',
  },
  journal: {
    title: 'Nutrition',
    back: 'Back to journal',
    today: 'Today',
    yesterday: 'Yesterday',
    tomorrow: 'Tomorrow',
    previousDay: 'Previous day',
    nextDay: 'Next day',
    remaining: 'Remaining',
    over: 'Over',
    target: 'Target',
    eaten: 'Eaten',
    planned: 'Planned',
    noTarget: 'No calorie target',
    targetFromCoach: 'Targets come from your coach’s plan.',
    macrosTitle: 'Macros',
    macroOf: '{{value}} of {{target}}',
    addFood: 'Add food',
    addToMeal: 'Add to {{meal}}',
    planLink: 'See full plan',
    noPlanTitle: 'No plan for this day',
    noPlanBody: 'You can still log what you eat. Your coach will see it.',
    readOnly: 'This day can no longer be edited.',
    adherence: '{{done}} of {{total}} planned items done',
    prescribed: 'Prescribed',
    markEaten: 'I ate it',
    change: 'Change',
    skip: 'Skip',
    undo: 'Undo',
    statusEaten: 'Eaten',
    statusReplaced: 'Changed to {{food}}',
    statusSkipped: 'Skipped',
    extraEntry: 'Extra',
    edit: 'Edit',
    delete: 'Delete',
    actionFailed: 'That did not save. Check your connection and try again.',
    kcalShort: 'kcal',
  },
  addSheet: {
    title: 'Add food',
    description: 'Choose how to find what you ate.',
    database: 'Food database',
    databaseHint: 'Search your plan, recent foods and the catalog',
    barcode: 'Scan barcode',
    barcodeHint: 'Packaged products',
    photo: 'Scan meal',
    photoBeta: 'Beta',
    photoHint: 'Coming soon: suggests foods from a photo for you to confirm.',
  },
  search: {
    title: 'Find food',
    placeholder: 'Search food',
    tabAll: 'All foods',
    tabPlan: 'In my plan',
    tabRecent: 'Recent',
    createOwn: 'Create food',
    per100: '{{kcal}} per 100 g',
    perPortion: '{{kcal}} per {{portion}}',
    inPlan: 'In your plan',
    own: 'Yours',
    empty: 'No foods found.',
    emptyRecent: 'Foods you log will appear here.',
    emptyPlan: 'Your plan has no foods for today.',
    loadMore: 'Load more',
    replacing: 'Changing: {{food}}',
  },
  food: {
    title: 'Food',
    mealType: 'Meal',
    portionUnit: 'Portion',
    amount: 'Amount',
    grams: 'g',
    mainMacros: 'Main macros',
    calories: 'Calories',
    otherNutrients: 'Other nutrients',
    unknown: '—',
    save: 'Add to journal',
    update: 'Save changes',
    saving: 'Saving…',
    prescribedAmount: 'Prescribed: {{amount}}',
    sourceOpenFoodFacts: 'Data from Open Food Facts (ODbL).',
    sourceUsda: 'Data from USDA FoodData Central.',
    ownFood: 'Your own food. Only you and your coach see it.',
    invalidAmount: 'Enter an amount greater than 0.',
    notFound: 'This food is not available.',
  },
  newFood: {
    title: 'New food',
    description: 'Copy the values from the label for one portion.',
    name: 'Food name',
    brand: 'Brand (optional)',
    portionLabel: 'Portion name (optional)',
    portionLabelPlaceholder: 'e.g. 1 bar',
    portionGrams: 'Portion size (g)',
    calories: 'Calories (kcal)',
    protein: 'Protein (g)',
    carbs: 'Carbs (g)',
    fat: 'Fat (g)',
    fiber: 'Fiber (g, optional)',
    save: 'Create food',
    saving: 'Creating…',
    invalid: 'Check the name, portion size and nutrition values.',
  },
  barcode: {
    title: 'Scan barcode',
    description: 'Point the camera at the barcode, or type the number.',
    startCamera: 'Use camera',
    stopCamera: 'Stop camera',
    cameraUnsupported: 'This browser cannot scan with the camera. Type the number instead.',
    cameraDenied: 'Camera access was denied. Type the number instead.',
    manualLabel: 'Barcode number',
    lookup: 'Find product',
    looking: 'Searching…',
    notFound: 'We could not find that product.',
    noData: 'That product has no usable nutrition information.',
    unavailable: 'Product search is unavailable right now. Try again later.',
    invalid: 'Enter 8 to 14 digits.',
  },
  error: {
    retry: 'Try again',
    retrying: 'Trying again…',
    network: 'The nutrition plan could not be loaded. Check your connection and try again.',
  },
} as const;

registerEnglishNamespace('clientNutrition', clientNutritionCopySource);
export const clientNutritionCopy = createLiveCopy<typeof clientNutritionCopySource>('clientNutrition');

export function useClientNutritionCopy() {
  return useLiveCopy<typeof clientNutritionCopySource>('clientNutrition');
}
