import { createLiveCopy, registerEnglishNamespace } from '@/i18n/live-copy';
import { useLiveCopy } from '@/i18n/use-live-copy';

export const adminWorkspaceCopySource = {
  loadingLabel: 'Loading admin workspace',
  retry: 'Try again',
  retrying: 'Retrying...',
  save: 'Save',
  saving: 'Saving...',
  create: 'Create',
  creating: 'Creating...',
  cancel: 'Cancel',
  search: 'Search',
  filters: 'Filters',
  clearFilters: 'Clear filters',
  previous: 'Previous',
  next: 'Next',
  page: 'Page',
  notSet: 'Not set',
  all: 'All',
  close: 'Close',
  optional: 'Optional',
  status: {
    ACTIVE: 'Active',
    DISABLED: 'Disabled',
    ARCHIVED: 'Archived',
    READY: 'Ready',
    PENDING_UPLOAD: 'Upload pending',
    FAILED: 'Failed',
  },
  common: {
    email: 'Email',
    password: 'Temporary password',
    firstName: 'First name',
    lastName: 'Last name',
    phone: 'Phone',
    name: 'Name',
    created: 'Created',
    updated: 'Updated',
    bytes: 'bytes',
    actions: 'Actions',
    open: 'Open',
    edit: 'Edit',
    activate: 'Activate',
    disable: 'Disable',
    archive: 'Archive',
    delete: 'Delete',
    restore: 'Restore',
    active: 'Active',
    disabled: 'Disabled',
    searchPlaceholder: 'Search...',
    emptyFiltered: 'No records match these filters.',
    required: 'Required',
    conflictTitle: 'Action could not be completed',
    conflictBody: 'The record changed or conflicts with another rule. Refresh and try again.',
    noMatchesTitle: 'No matches',
    noMatchesBody: 'Nothing matches the current search or filters.',
    showing: 'Showing {{from}}–{{to}} of {{total}}',
    status: 'Status',
    fieldRequired: 'This field is required.',
    invalidEmail: 'Enter a valid email address.',
    passwordLength: 'Use 12 to 128 characters.',
    tooLong: 'Use at most {{max}} characters.',
    nameLength: 'Use 2 to {{max}} characters.',
    numberRange: 'Enter a number from {{min}} to {{max}}.',
    checkFields: 'Review the highlighted fields and try again.',
    emailInUse: 'An account already uses this email address.',
    passwordHint: 'At least 12 characters. Share it privately; it is not shown again.',
  },
  dashboard: {
    title: 'Admin Dashboard',
    description: 'System counts for accounts, assignments, active plans, sessions, and submitted check-ins.',
    loadingLabel: 'Loading admin dashboard',
    activeTrainers: 'Active trainers',
    activeClients: 'Active clients',
    assignedClients: 'Assigned clients',
    unassignedClients: 'Unassigned clients',
    activeTrainingPlans: 'Active training plans',
    activeNutritionPlans: 'Active nutrition plans',
    completedSessions: 'Completed sessions',
    pendingCheckIns: 'Pending check-ins',
    period: 'Reporting window',
    days7: '7 days',
    days30: '30 days',
    days90: '90 days',
    assignmentHealth: 'Assignment health',
    planCoverage: 'Active plan coverage',
    operations: 'Operational queue',
    coverageTitle: 'Trainer coverage',
    coverageBody: '{{assigned}} of {{active}} active clients have a current trainer.',
    noActiveClients: 'No active clients yet. Create a client account to start assigning trainers.',
    allAssigned: 'Every active client has a current trainer.',
    reviewUnassigned: 'Review assignments',
    accountsTitle: 'Accounts',
    manageTrainers: 'Manage trainers',
    manageClients: 'Manage clients',
    programsTitle: 'Programs and activity',
    sessionsInWindow: 'Completed sessions, last {{days}} days',
    pendingCheckInsHint: 'Submitted check-ins waiting for trainer review.',
  },
  trainers: {
    title: 'Trainers',
    description: 'Create trainer accounts, maintain profile details, and control platform access.',
    loadingLabel: 'Loading trainers',
    emptyTitle: 'No trainer accounts',
    emptyBody: 'Create the first trainer account so clients can be assigned.',
    newTrainer: 'New trainer',
    editTrainer: 'Edit trainer',
    detailTitle: 'Trainer profile',
    professionalTitle: 'Professional title',
    bio: 'Bio',
    searchLabel: 'Search trainers',
    searchPlaceholder: 'Name or email',
    statusFilter: 'Status',
    disableTitle: 'Disable trainer?',
    disableBody: 'The trainer will not be able to authenticate. Existing assignments remain stored.',
    activateTitle: 'Activate trainer?',
    activateBody: 'The trainer can authenticate again. Assignment history is unchanged.',
    createdToast: 'Trainer created',
    savedToast: 'Trainer updated',
    statusToast: 'Trainer status updated',
    backToList: 'All trainers',
    assignedClientsNote: 'Current clients for this trainer are shown on each client profile and on the Assignments page.',
  },
  clients: {
    title: 'Clients',
    description: 'Create client accounts, maintain profile details, and monitor assignment state.',
    loadingLabel: 'Loading clients',
    emptyTitle: 'No client accounts',
    emptyBody: 'Create a client account, then assign a trainer when ready.',
    newClient: 'New client',
    editClient: 'Edit client',
    detailTitle: 'Client profile',
    searchLabel: 'Search clients',
    searchPlaceholder: 'Name or email',
    statusFilter: 'Status',
    goalFilter: 'Goal',
    experienceFilter: 'Experience',
    dateOfBirth: 'Date of birth',
    primaryGoal: 'Primary goal',
    experienceLevel: 'Experience',
    goalNotes: 'Goal notes',
    assignment: 'Trainer assignment',
    currentTrainer: 'Current trainer',
    unassigned: 'Unassigned',
    assignTrainer: 'Assign trainer',
    changeTrainer: 'Change trainer',
    removeAssignment: 'End assignment',
    removeTitle: 'End trainer assignment?',
    removeBody: 'The current assignment will end and remain in assignment history.',
    createdToast: 'Client created',
    savedToast: 'Client updated',
    statusToast: 'Client status updated',
    assignedToast: 'Trainer assignment updated',
    unassignedToast: 'Trainer assignment ended',
    disableTitle: 'Disable client?',
    disableBody: 'The client will not be able to authenticate. Assignment history remains stored.',
    activateTitle: 'Activate client?',
    activateBody: 'The client can authenticate again. Assignment history is unchanged.',
    backToList: 'All clients',
    assignedSince: 'Since {{date}}',
    assignDisabledHint: 'Activate this client before assigning a trainer.',
    reassignNote: 'Changing the trainer ends the current assignment and starts a new one. History keeps both.',
    currentTrainerOption: '{{name}} (current)',
    trainerFilter: 'Filter trainers',
    trainerFilterPlaceholder: 'Name or email',
    noActiveTrainers: 'No active trainers match. Create or activate a trainer first.',
    loadingTrainers: 'Loading trainers',
    assignmentConflict: 'The client or trainer is disabled, or the assignment changed. Refresh and try again.',
    historyEmpty: 'No assignments yet.',
    assignmentUnavailable: 'The current assignment could not be loaded.',
  },
  assignments: {
    title: 'Assignments',
    description: 'Review current trainer ownership and manage one active trainer per client.',
    loadingLabel: 'Loading assignments',
    emptyTitle: 'No clients to assign',
    emptyBody: 'Client accounts appear here after they are created.',
    client: 'Client',
    trainer: 'Trainer',
    workload: 'Workload',
    history: 'Assignment history',
    assignedAt: 'Assigned',
    endedAt: 'Ended',
    activeAssignment: 'Current',
    pastAssignment: 'Historical',
    pickTrainer: 'Choose trainer',
    noTrainer: 'No trainer',
    openClient: 'Open client',
    summary: '{{assigned}} assigned · {{unassigned}} unassigned across all active clients',
    activeOnlyNote: 'Only active clients are listed. Disabled clients cannot be assigned.',
    assign: 'Assign',
    change: 'Change',
    loadingTrainer: 'Loading trainer',
    trainerUnavailable: 'Could not load',
  },
  exercises: {
    title: 'Exercises',
    description: 'Operate the shared exercise catalog and manage Admin-authorized demonstration media.',
    loadingLabel: 'Loading exercises',
    emptyTitle: 'No exercises',
    emptyBody: 'Create catalog exercises for trainers to prescribe.',
    newExercise: 'New exercise',
    editExercise: 'Edit exercise',
    detailTitle: 'Exercise detail',
    searchLabel: 'Search exercises',
    muscle: 'Primary muscle',
    equipment: 'Equipment',
    difficulty: 'Difficulty',
    descriptionLabel: 'Description',
    instructions: 'Instructions',
    owner: 'Owner user ID',
    creator: 'Creator',
    media: 'Private media',
    uploadMedia: 'Upload media',
    mediaHint: 'Files stay private; access URLs are short-lived and loaded only for display.',
    file: 'File',
    displayOrder: 'Display order',
    video: 'Video',
    image: 'Image',
    mediaEmpty: 'No media for this exercise.',
    archiveTitle: 'Archive exercise?',
    archiveBody: 'Archived exercises stay stored but cannot be used for new prescriptions.',
    activateTitle: 'Reactivate exercise?',
    activateBody: 'The exercise returns to the active catalog.',
    deleteMediaTitle: 'Delete media?',
    deleteMediaBody: 'This removes the private object and its catalog row.',
    createdToast: 'Exercise created',
    savedToast: 'Exercise updated',
    statusToast: 'Exercise status updated',
    uploadedToast: 'Media uploaded',
    mediaDeletedToast: 'Media deleted',
    uploadFailed: 'The file could not be stored. Try again.',
    backToList: 'All exercises',
    source: 'Source',
    createdByYou: 'Created by you',
    createdByOther: 'Created by another account',
    otherOwnerWarning: 'Another account created this exercise. Changes apply everywhere it is used.',
    nameInUse: 'An exercise with this name already exists.',
    archivedConflict: 'This exercise is archived. Reactivate it before uploading media.',
    mediaLimit: 'This exercise has reached its media limit.',
    mediaConflict: 'The upload could not be completed. Try again.',
    chooseFile: 'Choose file',
    noFileChosen: 'No file chosen',
    fileTypes: 'MP4, WebM, MOV, JPEG, PNG or WebP.',
    unsupportedFile: 'Choose an MP4, WebM, MOV, JPEG, PNG or WebP file.',
    closePreview: 'Close preview',
    opening: 'Opening...',
    uploading: 'Uploading...',
    archivedMediaHint: 'Reactivate the exercise to upload new media.',
    deleteMediaLabel: 'Delete {{name}}',
    openMediaLabel: 'Open {{name}}',
  },
  foods: {
    title: 'Foods',
    description: 'Manage the per-100 g nutrition catalog used in prescribed meal plans.',
    loadingLabel: 'Loading foods',
    emptyTitle: 'No foods',
    emptyBody: 'Create foods with canonical per-100 g nutrition values.',
    newFood: 'New food',
    editFood: 'Edit food',
    detailTitle: 'Food detail',
    searchLabel: 'Search foods',
    brand: 'Brand',
    descriptionLabel: 'Description',
    per100: 'Per 100 g',
    calories: 'Calories',
    protein: 'Protein',
    carbs: 'Carbohydrates',
    fat: 'Fat',
    fiber: 'Fiber',
    archiveTitle: 'Archive food?',
    archiveBody: 'Archived foods stay stored but cannot be used for new plan snapshots.',
    activateTitle: 'Reactivate food?',
    activateBody: 'The food returns to the active nutrition catalog.',
    createdToast: 'Food created',
    savedToast: 'Food updated',
    statusToast: 'Food status updated',
    backToList: 'All foods',
    kcal: 'kcal',
    grams: 'g',
    per100Hint: 'All values are per 100 g.',
  },
  goals: {
    FAT_LOSS: 'Fat loss',
    MUSCLE_GAIN: 'Muscle gain',
    STRENGTH: 'Strength',
    GENERAL_FITNESS: 'General fitness',
    MAINTENANCE: 'Maintenance',
    OTHER: 'Other',
  },
  experience: {
    BEGINNER: 'Beginner',
    INTERMEDIATE: 'Intermediate',
    ADVANCED: 'Advanced',
  },
  muscles: {
    CHEST: 'Chest',
    BACK: 'Back',
    SHOULDERS: 'Shoulders',
    BICEPS: 'Biceps',
    TRICEPS: 'Triceps',
    FOREARMS: 'Forearms',
    QUADRICEPS: 'Quadriceps',
    HAMSTRINGS: 'Hamstrings',
    GLUTES: 'Glutes',
    CALVES: 'Calves',
    CORE: 'Core',
    FULL_BODY: 'Full body',
    CARDIO: 'Cardio',
    OTHER: 'Other',
  },
  equipment: {
    BODYWEIGHT: 'Bodyweight',
    BARBELL: 'Barbell',
    DUMBBELL: 'Dumbbell',
    MACHINE: 'Machine',
    CABLE: 'Cable',
    KETTLEBELL: 'Kettlebell',
    RESISTANCE_BAND: 'Resistance band',
    EZ_BAR: 'EZ bar',
    TRAP_BAR: 'Trap bar',
    CARDIO_MACHINE: 'Cardio machine',
    OTHER: 'Other',
  },
  difficulty: {
    BEGINNER: 'Beginner',
    INTERMEDIATE: 'Intermediate',
    ADVANCED: 'Advanced',
  },
} as const;

registerEnglishNamespace('adminWorkspace', adminWorkspaceCopySource);
export const adminWorkspaceCopy = createLiveCopy<typeof adminWorkspaceCopySource>('adminWorkspace');

export function useAdminWorkspaceCopy() {
  return useLiveCopy<typeof adminWorkspaceCopySource>('adminWorkspace');
}

export type AdminWorkspaceCopy = ReturnType<typeof useAdminWorkspaceCopy>;
