export enum ClientPrimaryGoal {
  FAT_LOSS = 'FAT_LOSS',
  MUSCLE_GAIN = 'MUSCLE_GAIN',
  STRENGTH = 'STRENGTH',
  GENERAL_FITNESS = 'GENERAL_FITNESS',
  MAINTENANCE = 'MAINTENANCE',
  OTHER = 'OTHER',
}
