import { createLiveCopy, registerEnglishNamespace } from '@/i18n/live-copy';
import { useLiveCopy } from '@/i18n/use-live-copy';

export const clientProgressCopySource = {
  title: 'Progress',
  description: 'Completed training in the selected period.',
  loadingLabel: 'Loading progress',
  loadingBody: 'Loading body measurements',
  loadingExercises: 'Loading exercises',
  loadingDetail: 'Loading exercise progress',
  periodLabel: 'Time period',
  periods: {
    7: '7D',
    30: '30D',
    90: '90D',
    180: '6M',
    365: '1Y',
  },
  periodAria: {
    7: 'Last 7 days',
    30: 'Last 30 days',
    90: 'Last 90 days',
    180: 'Last 6 months',
    365: 'Last year',
  },
  overview: {
    title: 'Training in this period',
    empty: 'No completed sessions in this period yet.',
    emptyHint: 'Completed workouts appear here. In-progress and cancelled sessions are not counted.',
    sessions: 'Sessions',
    volume: 'External load volume',
    volumeHint: 'Sum of load × reps when both were recorded. Bodyweight sets without a load are not included.',
    vsPrevious: 'vs previous period',
    noComparison: 'No previous-period comparison yet.',
    lastSession: 'Last completed',
    firstSession: 'First completed',
  },
  consistency: {
    title: 'Consistency',
    description: 'Completed training volume in this period.',
    sets: 'Sets',
    reps: 'Reps',
    duration: 'Duration work',
    exercises: 'Exercises',
    empty: 'No completed sets in this period.',
  },
  body: {
    title: 'Body',
    description: 'Measurements recorded in this period.',
    empty: 'No measurements in this period.',
    emptyHint: 'Body entries and photos are managed on Body progress.',
    weight: 'Weight',
    waist: 'Waist',
    latest: 'Latest',
    change: 'Change in this period',
    unchanged: 'Unchanged',
    chartLabel: 'Body weight',
    chartSummary: 'Body weight across measurements in this period.',
    viewBody: 'View body progress',
    onePoint: 'One measurement in this period. A trend appears after another entry.',
  },
  exercises: {
    title: 'Exercises',
    description: 'Exercises with completed sets in this period.',
    empty: 'No exercise history in this period.',
    sessions: 'sessions',
    session: 'session',
    last: 'Last',
    reps: 'Reps',
    duration: 'Duration',
    archived: 'Archived',
    highestLoad: 'Highest load',
    highestDuration: 'Longest set',
    more: 'More exercises',
  },
  detail: {
    back: 'Back to progress',
    notFound: 'No completed performance for this exercise.',
    notFoundHint: 'This exercise has no completed sets in the selected period, or it is not available.',
    forbidden: 'This exercise progress is not available.',
    invalidId: 'That exercise link is not valid.',
    repsTitle: 'Reps work',
    durationTitle: 'Duration work',
    highestLoad: 'Highest load in this period',
    highestReps: 'Highest reps in this period',
    estimated1Rm: 'Highest estimated 1RM in this period',
    estimated1RmHint: 'Epley estimate from recorded sets. Not a tested 1RM.',
    highestDuration: 'Longest set in this period',
    firstAchieved: 'First recorded',
    volumeChart: 'External load volume',
    loadChart: 'Best load',
    durationChart: 'Session duration',
    history: 'Session history',
    noHistory: 'No session history on this page.',
    set: 'Set',
    load: 'Load',
    reps: 'Reps',
    duration: 'Duration',
    visualizationNote: 'Exercise media and 3D are not available on Client progress.',
  },
  error: {
    retry: 'Try again',
    retrying: 'Trying again…',
    network: 'Progress could not be loaded. Check your connection and try again.',
    section: 'This section could not be loaded.',
  },
} as const;

registerEnglishNamespace('clientProgress', clientProgressCopySource);
export const clientProgressCopy = createLiveCopy<typeof clientProgressCopySource>('clientProgress');

export function useClientProgressCopy() {
  return useLiveCopy<typeof clientProgressCopySource>('clientProgress');
}
