export const PROGRESS_LIST_DEFAULT_PAGE = 1;
export const PROGRESS_LIST_DEFAULT_LIMIT = 20;
export const PROGRESS_LIST_MAX_LIMIT = 100;
export const PROGRESS_SEARCH_MAX_LENGTH = 100;
export const PROGRESS_EPLEY_MAX_REPS = 10;
export const PROGRESS_METRIC_SCALE = 2;
