export enum ActivityEventType {
  CHECK_IN_SUBMITTED = 'CHECK_IN_SUBMITTED',
  CHECK_IN_REVIEWED = 'CHECK_IN_REVIEWED',
  TRAINING_PLAN_ACTIVATED = 'TRAINING_PLAN_ACTIVATED',
  NUTRITION_PLAN_ACTIVATED = 'NUTRITION_PLAN_ACTIVATED',
}
