import { createLiveCopy, registerEnglishNamespace } from '@/i18n/live-copy';
import { useLiveCopy } from '@/i18n/use-live-copy';

export const clientBodyCopySource = {
  title: 'Body progress',
  description: 'Record measurements and private progress photos. Values are what you entered, not a health score.',
  loadingLabel: 'Loading body progress',
  measurements: {
    title: 'Measurements',
    description: 'Kilograms, centimeters, and body-fat percentage as you recorded them.',
    emptyTitle: 'No measurements yet.',
    emptyBody: 'Add a measurement to keep a history. At least one number is required.',
    add: 'Add measurement',
    edit: 'Edit',
    latest: 'Latest',
    history: 'History',
    save: 'Save measurement',
    saving: 'Saving…',
    saved: 'Measurement saved.',
    updated: 'Measurement updated.',
    cancel: 'Cancel',
    createTitle: 'New measurement',
    editTitle: 'Edit measurement',
    formDescription: 'Leave unused fields blank. Notes alone are not a measurement.',
    measuredAt: 'Recorded at',
    measuredAtHint: 'Optional. Leave blank to use the current time.',
    notes: 'Notes',
    notesHint: 'Optional. Not a substitute for a number.',
    atLeastOne: 'Enter at least one measurement.',
    loadMore: 'Load more',
    page: 'Page',
  },
  metrics: {
    bodyWeightKg: 'Weight',
    bodyFatPercentage: 'Body fat',
    neckCm: 'Neck',
    shouldersCm: 'Shoulders',
    chestCm: 'Chest',
    waistCm: 'Waist',
    hipsCm: 'Hips',
    leftArmCm: 'Left arm',
    rightArmCm: 'Right arm',
    leftThighCm: 'Left thigh',
    rightThighCm: 'Right thigh',
    leftCalfCm: 'Left calf',
    rightCalfCm: 'Right calf',
  },
  units: {
    kg: 'kg',
    cm: 'cm',
    percent: '%',
  },
  photos: {
    title: 'Progress photos',
    description: 'Private photos. Signed links expire and are not stored on this device.',
    emptyTitle: 'No ready photos yet.',
    emptyBody: 'Upload a JPEG, PNG, or WebP photo. Your coach can review assigned photos later.',
    upload: 'Upload photo',
    add: 'Add photo',
    uploading: 'Uploading…',
    uploaded: 'Photo uploaded.',
    pose: 'Pose',
    file: 'Photo file',
    chooseFile: 'Choose photo',
    noFile: 'No file selected',
    captureAt: 'Captured at',
    linkMeasurement: 'Link to a measurement',
    linkNone: 'Not linked',
    mimeHint: 'JPEG, PNG, or WebP. Maximum 10 MB.',
    pending: 'Upload pending',
    failed: 'Upload failed',
    ready: 'Ready',
    delete: 'Delete photo',
    deleteTitle: 'Delete this photo?',
    deleteBody: 'The photo is removed from private storage. This cannot be undone.',
    deleting: 'Deleting…',
    deleted: 'Photo deleted.',
    confirmDelete: 'Delete photo',
    cancel: 'Keep photo',
    close: 'Cancel',
    retryUpload: 'Try again',
    loadMore: 'Load more photos',
    missingFile: 'Choose a photo to upload.',
    tooLarge: 'That file is larger than 10 MB.',
    badType: 'Use a JPEG, PNG, or WebP file.',
  },
  pose: {
    FRONT: 'Front',
    SIDE: 'Side',
    BACK: 'Back',
    OTHER: 'Other',
  },
  compare: {
    title: 'Compare',
    description: 'Two ready photos, side by side. Pick any pair — the app does not score them.',
    first: 'Earlier photo',
    second: 'Later photo',
    choose: 'Choose a photo',
    needTwo: 'Upload at least two ready photos to compare.',
    same: 'Choose two different photos.',
  },
  image: {
    alt: 'Progress photo',
    loading: 'Loading photo',
    failed: 'The photo could not be shown. Try again.',
    retry: 'Reload photo',
    retrying: 'Reloading…',
  },
  error: {
    retry: 'Try again',
    retrying: 'Trying again…',
    network: 'Body progress could not be loaded. Check your connection and try again.',
  },
} as const;

registerEnglishNamespace('clientBody', clientBodyCopySource);
export const clientBodyCopy = createLiveCopy<typeof clientBodyCopySource>('clientBody');

export function useClientBodyCopy() {
  return useLiveCopy<typeof clientBodyCopySource>('clientBody');
}
