import { createLiveCopy, registerEnglishNamespace } from '@/i18n/live-copy';
import { useLiveCopy } from '@/i18n/use-live-copy';

export const trainerWorkspaceCopySource = {
  loadingLabel: 'Loading workspace',
  retry: 'Try again',
  retrying: 'Retrying…',
  save: 'Save',
  saving: 'Saving…',
  create: 'Create',
  creating: 'Creating…',
  activate: 'Activate',
  archive: 'Archive',
  previous: 'Previous',
  next: 'Next',
  search: 'Search',
  filters: 'Filters',
  clearFilters: 'Clear filters',
  noResults: 'No matching results.',
  unnamed: 'Unnamed',
  notSet: 'Not set',
  yes: 'Yes',
  no: 'No',
  status: {
    ACTIVE: 'Active',
    DISABLED: 'Disabled',
    DRAFT: 'Draft',
    ARCHIVED: 'Archived',
    SUBMITTED: 'Waiting for review',
    REVIEWED: 'Reviewed',
    READY: 'Ready',
    PENDING_UPLOAD: 'Upload pending',
    FAILED: 'Failed',
    COMPLETED: 'Completed',
    IN_PROGRESS: 'In progress',
    CANCELLED: 'Cancelled',
  },
  dashboard: {
    title: 'Dashboard',
    description: 'What needs attention across assigned Clients.',
    loadingLabel: 'Loading dashboard',
    emptyTitle: 'No assigned Clients yet',
    emptyBody:
      'Clients appear here after an Admin assigns them to you. You cannot create Client accounts.',
    attentionTitle: 'Needs attention',
    pendingCheckIns: 'Pending check-ins',
    pendingCheckInsEmpty: 'No submitted check-ins waiting for review.',
    reviewCheckIn: 'Review check-in',
    inactivityTitle: 'No recent completed training',
    inactivityHint: 'Clients with no completed session in the selected window, including those who have never completed one.',
    inactivityDays: 'Inactivity window',
    missingTraining: 'No active training plan',
    missingNutrition: 'No active nutrition plan',
    noneInList: 'None right now.',
    recentSessions: 'Recent completed sessions',
    recentSessionsEmpty: 'No completed sessions yet.',
    sets: 'sets',
    countsTitle: 'Assigned Clients',
    activeClients: 'Active',
    disabledClients: 'Disabled accounts',
    openClient: 'Open Client',
    viewAllClients: 'View all Clients',
    viewCheckIns: 'Open check-in queue',
  },
  clients: {
    title: 'Clients',
    description: 'Assigned Clients and the next coaching action.',
    loadingLabel: 'Loading Clients',
    emptyTitle: 'No assigned Clients',
    emptyBody:
      'When an Admin assigns Clients to you, they will appear here. Trainers cannot create Client accounts.',
    searchLabel: 'Search by name',
    searchPlaceholder: 'Name',
    pageLabel: 'Page',
    trainingPlan: 'Training plan',
    nutritionPlan: 'Nutrition plan',
    lastWorkout: 'Last completed workout',
    checkIn: 'Check-in',
    pendingReview: 'Needs review',
    noPending: 'None pending',
    hasPlan: 'Active plan',
    noPlan: 'No active plan',
    never: 'Never',
    open: 'Open',
    filterTraining: 'Training plan',
    filterNutrition: 'Nutrition plan',
    filterCheckIn: 'Pending check-in',
    filterInactivity: 'No completed workout in',
    any: 'Any',
    with: 'Has',
    without: 'Missing',
    days7: '7 days',
    days14: '14 days',
    days30: '30 days',
  },
  workspace: {
    contextLabel: 'Working with',
    backToClients: 'All Clients',
    overview: 'Overview',
    training: 'Training',
    progress: 'Progress',
    body: 'Body',
    nutrition: 'Nutrition',
    checkIns: 'Check-ins',
    loadingClient: 'Loading Client',
    notFoundTitle: 'Client not available',
    notFoundBody: 'This Client is not currently assigned to you.',
    disabledAccount: 'Account disabled',
    goal: 'Goal',
    experience: 'Experience',
    email: 'Email',
    phone: 'Phone',
    notes: 'Goal notes',
    memberSince: 'Profile created',
  },
  overview: {
    title: 'Overview',
    description: 'Coaching snapshot for this Client.',
    loadingLabel: 'Loading overview',
    snapshot: 'Current assignment',
    training: 'Training',
    nutrition: 'Nutrition',
    checkIn: 'Latest submitted check-in',
    lastWorkout: 'Last completed workout',
    lastMeasurement: 'Latest measurement',
    goTraining: 'Manage training',
    goNutrition: 'Manage nutrition',
    goCheckIns: 'Open check-ins',
    goProgress: 'Review progress',
    goBody: 'Review body progress',
    recentSessions: 'Recent sessions',
    sessionsEmpty: 'No workout sessions recorded.',
  },
  progress: {
    title: 'Progress',
    description: 'Completed training facts for this Client.',
    loadingLabel: 'Loading progress',
    empty: 'No completed training in this window.',
    period: 'Period',
    sessions: 'Completed sessions',
    sets: 'Performed sets',
    volume: 'External load volume',
    reps: 'Total reps',
    duration: 'Duration work',
    exercises: 'Exercises performed',
    lastSession: 'Last completed session',
    vsPrevious: 'vs previous window',
    noComparison: 'No previous window to compare.',
    exerciseList: 'Exercises',
    exerciseEmpty: 'No exercise history in this window.',
    openExercise: 'Open exercise',
    bodyWeight: 'Body weight history',
    bodyEmpty: 'No body-weight records in this window.',
  },
  body: {
    title: 'Body progress',
    description: 'Measurements and private photos you are authorized to review.',
    loadingLabel: 'Loading body progress',
    measurements: 'Measurements',
    measurementsEmpty: 'No measurements recorded.',
    photos: 'Progress photos',
    photosEmpty: 'No ready progress photos.',
    photosForbidden:
      'Progress photos are not available for this Client.',
    weight: 'Body weight',
    bodyFat: 'Body fat',
    notes: 'Notes',
    pose: 'Pose',
    captured: 'Captured',
    imageLoading: 'Loading photo',
    imageFailed: 'This photo could not be loaded.',
    imageRetry: 'Retry',
  },
  training: {
    title: 'Training',
    description: 'Plans assigned to this Client. Workouts come from templates.',
    loadingLabel: 'Loading training plans',
    emptyTitle: 'No training plans',
    emptyBody: 'Create a draft plan, add workouts from templates, then activate it.',
    create: 'New plan',
    name: 'Plan name',
    descriptionLabel: 'Description',
    startDate: 'Start date',
    endDate: 'End date',
    workouts: 'Workouts',
    noWorkouts: 'No workouts in this plan yet.',
    addWorkout: 'Add workout from template',
    template: 'Template',
    scheduledDay: 'Scheduled day',
    unscheduled: 'No weekday',
    notes: 'Notes',
    saveWorkouts: 'Save workouts',
    activateHint: 'Activating archives any previous active plan for this Client.',
    archiveHint: 'Archiving retires this plan. It cannot return to draft.',
    prescription: 'Prescription',
    sets: 'Sets',
    reps: 'Reps',
    duration: 'Duration (sec)',
    rest: 'Rest (sec)',
    load: 'Target load (kg)',
    rpe: 'RPE',
    rir: 'RIR',
    tempo: 'Tempo',
    saveExercise: 'Save exercise',
    openPlan: 'Open plan',
  },
  templates: {
    title: 'Training',
    description: 'Create and manage reusable workout templates for Client plans.',
    loadingLabel: 'Loading templates',
    libraryTitle: 'Workout templates',
    emptyTitle: 'No workout templates yet',
    emptyBody: 'Create reusable workouts and add them to your Clients’ training plans.',
    emptyCreate: 'Create template',
    noMatches: 'No templates match these filters.',
    create: 'New template',
    createTitle: 'Create workout template',
    createDescription: 'Name the template. You can add exercises after it is created.',
    created: 'Template created',
    submitCreate: 'Create template',
    cancel: 'Cancel',
    name: 'Template name',
    nameRequired: 'Template name is required.',
    descriptionLabel: 'Description',
    searchLabel: 'Search templates',
    searchPlaceholder: 'Search templates…',
    exercises: 'Exercises',
    noExercises: 'No exercises yet.',
    builderEmptyTitle: 'No exercises yet',
    builderEmptyBody: 'Start building this workout by adding the first exercise.',
    addExercise: 'Add exercise',
    exerciseAdded: 'Exercise added',
    changeExercise: 'Change exercise',
    exercise: 'Exercise',
    saveExercises: 'Workout updated',
    savePrescription: 'Save prescription',
    editExercise: 'Edit',
    removeExercise: 'Remove',
    moveUp: 'Move up',
    moveDown: 'Move down',
    searchExercises: 'Search exercises',
    searchExercisesPlaceholder: 'Search exercises…',
    noExerciseMatches: 'No exercises match this search.',
    pickExercise: 'Choose an exercise',
    pickExerciseBody: 'Search the catalog, then set the prescription the Client will follow.',
    prescriptionTitle: 'Prescription',
    prescriptionType: 'Work type',
    repsType: 'Reps',
    durationType: 'Time',
    repsMin: 'Reps from',
    repsMax: 'Reps to',
    duration: 'Duration',
    durationHint: 'Seconds of work.',
    rest: 'Rest',
    restHint: 'Seconds. Zero means no rest.',
    intensity: 'Intensity',
    intensityNone: 'None',
    invalidPrescription: 'Check sets and rest.',
    invalidReps: 'Check the repetition range.',
    invalidDuration: 'Check duration.',
    invalidRpe: 'Check RPE (1.0–10.0).',
    invalidRir: 'Check RIR (0–10).',
    playDemo: 'Play demonstration',
    pauseDemo: 'Pause demonstration',
    mediaLoading: 'Loading demonstration',
    mediaEmpty: 'No demonstration media',
    mediaFailed: 'Demonstration could not be loaded.',
    mediaRetry: 'Retry',
    activateRequiresExercises: 'Add at least one exercise before activating.',
    activateHint: 'Activation publishes this template for Client plans. It cannot return to draft.',
    archiveHint: 'Archiving retires this template. You can reactivate it later.',
    archivedHint: 'This template is archived. Reactivate it to edit exercises.',
    statusFilter: 'Status',
    statusAll: 'All',
    updated: 'Updated',
    open: 'Open',
    openTemplate: 'Open template',
    close: 'Close',
    backToLibrary: 'Workout templates',
  },
  nutrition: {
    title: 'Nutrition',
    description: 'Prescribed meal plans. These are not food logs.',
    loadingLabel: 'Loading nutrition plans',
    emptyTitle: 'No nutrition plans',
    emptyBody: 'Create a draft plan, set targets and meals, then activate it.',
    create: 'New plan',
    name: 'Plan name',
    descriptionLabel: 'Description',
    targets: 'Prescribed daily targets',
    calories: 'Calories (kcal)',
    protein: 'Protein (g)',
    carbs: 'Carbohydrates (g)',
    fat: 'Fat (g)',
    meals: 'Meals',
    noMeals: 'No meals in this plan.',
    addMeal: 'Add meal',
    mealName: 'Meal name',
    mealType: 'Meal type',
    addItem: 'Add food',
    food: 'Food',
    quantity: 'Quantity (g)',
    saveMeals: 'Save meals',
    mealTotals: 'Meal-plan totals',
    targetDiff: 'Difference vs targets',
    prescribedHint: 'Targets are prescribed. Meal totals are derived from portions. Neither is intake.',
    openPlan: 'Open plan',
  },
  foods: {
    title: 'Nutrition',
    description: 'Foods used when building prescribed meal plans.',
    loadingLabel: 'Loading foods',
    emptyTitle: 'No foods',
    emptyBody: 'Create a food with per-100 g nutrition to use it in meal plans.',
    create: 'New food',
    name: 'Name',
    brand: 'Brand',
    per100: 'Per 100 g',
    open: 'Open',
  },
  checkIns: {
    title: 'Check-ins',
    description: 'Submitted and reviewed check-ins. Drafts are not shown.',
    queueTitle: 'Check-ins',
    queueDescription: 'Submitted check-ins waiting for review.',
    loadingLabel: 'Loading check-ins',
    emptyTitle: 'No check-ins to review',
    emptyBody: 'Submitted check-ins from assigned Clients appear here.',
    clientEmpty: 'This Client has no submitted or reviewed check-ins.',
    open: 'Open',
    period: 'Period',
    submitted: 'Submitted',
    review: 'Write review',
    feedback: 'Feedback',
    actionItems: 'Action items',
    submitReview: 'Submit review',
    updateReview: 'Update review',
    reviewed: 'Reviewed',
    ratings: 'Ratings',
    adherence: 'Adherence',
    notes: 'Notes',
    noResponses: 'No responses recorded.',
    fields: {
      sleepQuality: 'Sleep',
      energyLevel: 'Energy',
      stressLevel: 'Stress',
      hungerLevel: 'Hunger',
      recoveryLevel: 'Recovery',
      trainingAdherencePct: 'Training adherence',
      nutritionAdherencePct: 'Nutrition adherence',
      wins: 'Wins',
      challenges: 'Challenges',
      generalNotes: 'Notes',
    },
  },
  exercises: {
    title: 'Exercises',
    description: 'Search and select exercises for Client programs.',
    loadingLabel: 'Loading exercises',
    emptyTitle: 'No exercises',
    emptyBody: 'Create an exercise to use it in workout templates.',
    create: 'New exercise',
    createTitle: 'New exercise',
    createDescription: 'Add a catalog exercise Trainers can prescribe.',
    created: 'Exercise created',
    libraryHeading: 'Exercise library',
    searchPlaceholder: 'Search exercises…',
    allMuscles: 'All muscles',
    allEquipment: 'All equipment',
    allDifficulties: 'All difficulties',
    allStatuses: 'All statuses',
    name: 'Name',
    descriptionLabel: 'Description',
    instructions: 'Instructions',
    muscle: 'Primary muscle',
    muscleFilter: 'Muscle',
    equipment: 'Equipment',
    difficulty: 'Difficulty',
    media: 'Media',
    videoKind: 'Video',
    imageKind: 'Image',
    mediaEmpty: 'No ready media.',
    mediaHint:
      'Upload a demonstration for exercises you created. Files stay in private storage; signed access is loaded only to display them.',
    catalogReadOnly: 'Catalog demonstrations are read-only. Upload media on exercises you created.',
    archivedNoUpload: 'Archived exercises cannot receive new media.',
    createThenUpload: 'After creating the exercise, upload a demonstration on its detail page.',
    mediaStatus: 'Media status',
    upload: 'Upload media',
    file: 'File',
    mimeHint: 'MP4, WebM, or MOV up to 250 MB; JPEG, PNG, or WebP up to 10 MB. GIF is not supported.',
    missingFile: 'Choose a file to upload.',
    badType: 'Use MP4, WebM, MOV, JPEG, PNG, or WebP. GIF is not supported.',
    tooLarge: 'That file is larger than the allowed size.',
    videoLimit: 'This exercise already has the maximum number of videos.',
    imageLimit: 'This exercise already has the maximum number of images.',
    uploading: 'Uploading…',
    uploaded: 'Demonstration uploaded',
    uploadFailed: 'The file could not be stored. Try again.',
    delete: 'Delete',
    deleteTitle: 'Delete this media?',
    deleteBody: 'This removes the demonstration file from private storage. This cannot be undone.',
    confirmDelete: 'Delete media',
    deleting: 'Deleting…',
    deleted: 'Media deleted',
    cancel: 'Cancel',
    open: 'Open',
    viewDemonstration: 'View demonstration',
    playDemonstration: 'Play demonstration',
    pauseDemonstration: 'Pause demonstration',
    mediaFailed: 'Demonstration could not be loaded.',
    mediaRetry: 'Retry',
  },
  notifications: {
    title: 'Notifications',
    description: 'The notification inbox ships in a later phase.',
  },
  goals: {
    FAT_LOSS: 'Fat loss',
    MUSCLE_GAIN: 'Muscle gain',
    STRENGTH: 'Strength',
    GENERAL_FITNESS: 'General fitness',
    MAINTENANCE: 'Maintenance',
    OTHER: 'Other',
  },
  experience: {
    BEGINNER: 'Beginner',
    INTERMEDIATE: 'Intermediate',
    ADVANCED: 'Advanced',
  },
  days: {
    MONDAY: 'Monday',
    TUESDAY: 'Tuesday',
    WEDNESDAY: 'Wednesday',
    THURSDAY: 'Thursday',
    FRIDAY: 'Friday',
    SATURDAY: 'Saturday',
    SUNDAY: 'Sunday',
  },
  mealTypes: {
    BREAKFAST: 'Breakfast',
    LUNCH: 'Lunch',
    DINNER: 'Dinner',
    SNACK: 'Snack',
    OTHER: 'Other',
  },
  poses: {
    FRONT: 'Front',
    SIDE: 'Side',
    BACK: 'Back',
    OTHER: 'Other',
  },
} as const;

registerEnglishNamespace('trainerWorkspace', trainerWorkspaceCopySource);
export const trainerWorkspaceCopy = createLiveCopy<typeof trainerWorkspaceCopySource>('trainerWorkspace');

export function useTrainerWorkspaceCopy() {
  return useLiveCopy<typeof trainerWorkspaceCopySource>('trainerWorkspace');
}
